In [12]:
import pandas as pd

In [13]:
schools_complete_load = "C://Users/natha/Documents/BootCamp HW Assigments/Pandas Hw/pandas-challenge/schools_complete.csv"
students_complete_load = "C://Users/natha/Documents/BootCamp HW Assigments/Pandas Hw/pandas-challenge/students_complete.csv"

In [15]:
schools_data = pd.read_csv(schools_complete_load)
schools_data.head()

   School ID            school_name      type  size   budget
0          0      Huang High School  District  2917  1910635
1          1   Figueroa High School  District  2949  1884411
2          2    Shelton High School   Charter  1761  1056600
3          3  Hernandez High School  District  4635  3022020
4          4    Griffin High School   Charter  1468   917500

In [16]:
students_data = pd.read_csv(students_complete_load)
students_data.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [17]:
school_data_merged = pd.merge(students_data, schools_data, how="left", on=["school_name", "school_name"])
school_data_merged.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635

In [32]:
total_number_students =  school_data_merged["Student ID"].nunique()
j = 0
for i in school_data_merged["math_score"]:
    if i >= 70:
        j = j + 1
Math_Pass_Rate = j/total_number_students
j = 0
for i in school_data_merged["reading_score"]:
    if i >= 70:
        j = j + 1
Reading_Pass_Rate = j/total_number_students
district_df = pd.DataFrame([{"Total Schools": school_data_merged["school_name"].nunique(), "Total Students": total_number_students, "Total Budget": schools_data["budget"].sum(), "Average Math Score": (school_data_merged["math_score"].sum())/total_number_students, "Average Reading Score": (school_data_merged["reading_score"].sum())/total_number_students, "% Passing Math": Math_Pass_Rate, "% Passing Reading": Reading_Pass_Rate, "% Overall Passing Rate": (Math_Pass_Rate + Reading_Pass_Rate)/2}])
district_df2 = district_df[["Total Schools", "Total Students", "Total Budget", "Average Math Score", "Average Reading Score", "% Passing Math", "% Passing Reading", "% Overall Passing Rate"]]
district_df2

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
0,15,39170,24649428,78.985371,81.87784,0.749809,0.858055,0.803932

In [26]:
math_above = school_data_merged.loc[(school_data_merged["math_score"] >= 70) & (school_data_merged["reading_score"] >= 70)]
math_above[]

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635
11,11,Daniel Cooper,M,10th,Huang High School,78,77,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88,0,District,2917,1910635
17,17,Kimberly Santiago,F,9th,Huang High School,74,75,0,District,2917,1910635
19,19,Brandi Lyons,F,9th,Huang High School,89,80,0,District,2917,1910635
20,20,Lisa Davis,F,10th,Huang High School,91,89,0,District,2917,1910635
21,21,Kristen Lopez,F,10th,Huang High School,90,77,0,District,2917,1910635
22,22,Kimberly Stewart,F,11th,Huang High School,99,84,0,District,2917,1910635
24,24,Chelsea Griffith,F,11th,Huang High School,85,73,0,District,2917,1910635
25,25,Cesar Morris,M,9th,Huang High School,92,70,0,District,2917,1910635
29,29,Nicole Brown,F,12th,Huang High School,90,88,0,District,2917,1910635
30,30,Bobby Harris,M,9th,Huang High School,94,99,0,District,2917,1910635
32,32,Candace Phelps,F,11th,Huang High School,93,90,0,District,2917,1910635
36,36,Kevin Bailey,M,10th,Huang High School,76,76,0,District,2917,1910635
38,38,Kimberly Mercado,F,12th,Huang High School,73,77,0,District,2917,1910635
41,41,Jennifer Parks,F,11th,Huang High School,85,95,0,District,2917,1910635
47,47,Ellen Brown,F,11th,Huang High School,77,81,0,District,2917,1910635
49,49,Natalie Mitchell,F,10th,Huang High School,73,93,0,District,2917,1910635
50,50,Tiffany Gutierrez,F,10th,Huang High School,82,95,0,District,2917,1910635
55,55,Jerry Gordon,M,12th,Huang High School,95,71,0,District,2917,1910635
56,56,Michael Cox,M,11th,Huang High School,72,72,0,District,2917,1910635
58,58,Allison King,F,11th,Huang High School,74,84,0,District,2917,1910635
59,59,Theresa Meyer,F,9th,Huang High School,88,70,0,District,2917,1910635
66,66,Mr. Dylan Taylor MD,M,10th,Huang High School,77,93,0,District,2917,1910635
...,...,...,...,...,...,...,...,...,...,...,...
39139,39139,Catherine Lee,F,9th,Thomas High School,83,81,14,Charter,1635,1043130
39140,39140,Cheyenne Hernandez,F,9th,Thomas High School,76,99,14,Charter,1635,1043130
39141,39141,Jonathan Sullivan,M,10th,Thomas High School,86,93,14,Charter,1635,1043130
39142,39142,Deborah Higgins DDS,F,10th,Thomas High School,96,83,14,Charter,1635,1043130
39143,39143,Steven Jackson,M,11th,Thomas High School,71,93,14,Charter,1635,1043130
39144,39144,Cristian Webster,M,12th,Thomas High School,77,87,14,Charter,1635,1043130
39145,39145,Audrey Fry,F,10th,Thomas High School,94,74,14,Charter,1635,1043130
39147,39147,Raymond Hawkins,M,10th,Thomas High School,88,81,14,Charter,1635,1043130
39148,39148,Christopher Wilson,M,10th,Thomas High School,89,89,14,Charter,1635,1043130
39149,39149,Glenda Fletcher,F,11th,Thomas High School,82,93,14,Charter,1635,1043130
39150,39150,Jennifer Hamilton,F,11th,Thomas High School,80,75,14,Charter,1635,1043130
39151,39151,Shannon Williams,F,10th,Thomas High School,84,73,14,Charter,1635,1043130
39152,39152,Lori Moore,F,9th,Thomas High School,98,84,14,Charter,1635,1043130
39153,39153,William Hubbard,M,9th,Thomas High School,80,75,14,Charter,1635,1043130
39154,39154,Bradley Johnson,M,12th,Thomas High School,91,71,14,Charter,1635,1043130
39155,39155,John Brooks,M,10th,Thomas High School,92,98,14,Charter,1635,1043130
39156,39156,Stephanie Contreras,F,11th,Thomas High School,79,95,14,Charter,1635,1043130
39157,39157,Kristen Gonzalez,F,9th,Thomas High School,79,94,14,Charter,1635,1043130
39158,39158,Kari Holloway,F,10th,Thomas High School,87,90,14,Charter,1635,1043130
39159,39159,Kimberly Cabrera,F,11th,Thomas High School,85,72,14,Charter,1635,1043130
39160,39160,Katie Weaver,F,11th,Thomas High School,89,86,14,Charter,1635,1043130
39161,39161,April Reyes,F,10th,Thomas High School,70,84,14,Charter,1635,1043130
39162,39162,Derek Weeks,M,12th,Thomas High School,94,77,14,Charter,1635,1043130
39163,39163,John Reese,M,11th,Thomas High School,90,75,14,Charter,1635,1043130
39164,39164,Joseph Anthony,M,9th,Thomas High School,97,76,14,Charter,1635,1043130
39165,39165,Donna Howard,F,12th,Thomas High School,99,90,14,Charter,1635,1043130
39166,39166,Dawn Bell,F,10th,Thomas High School,95,70,14,Charter,1635,1043130
39167,39167,Rebecca Tanner,F,9th,Thomas High School,73,84,14,Charter,1635,1043130
39168,39168,Desiree Kidd,F,10th,Thomas High School,99,90,14,Charter,1635,1043130
39169,39169,Carolyn Jackson,F,11th,Thomas High School,95,75,14,Charter,1635,1043130